server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/video_streaming
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql

service:
  auth:
    url: http://auth-service:8085/login
  file-system:
    url: http://file-system-service:8083/upload

video:
  upload:
    dir: /videos
